# Use postgres/example user/password credentials
version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq-mensageria
    ports:
      - 5672:5672
      - 15672:15672    
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
     - CLUSTERED=false